containers:
  bedrock:
    # Backup the world "PrivateSMP" on the "bedrock_private" docker container
    - name: bedrock_private
      # Enables SSH. Password should match RCON_PASSWORD
      sshAddr: private:2222
      sshPassword: mygreatpassword
      worlds:
        - /bedrock_private/worlds/PrivateSMP
    # Backup the world "PublicSMP" on the "bedrock_public" docker container
    - name: bedrock_public
      # Enables SSH. Password should match RCON_PASSWORD
      sshAddr: public:2222
      sshPassword: mygreatpassword
      worlds:
        - /bedrock_public/worlds/PublicSMP
schedule:
  # This will perform a backup every 3 hours.
  # At most this will generate 8 backups a day.
  interval: 3h
trim:
  # Keep all backups for the last two days (today and yesterday)
  # Keep at least one backup for the last 14 days
  # Keep at least two backups per world
  trimDays: 2
  keepDays: 14
  minKeep: 2
