services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft images start before the backup
    depends_on:
      public:
        condition: service_healthy
        restart: true
      private:
        condition: service_healthy
        restart: true
    environment:
      # Local timezone to reduce confusion
      TZ: ${TZ:-America/Los_Angeles}
    volumes:
      - minecraft-backup:/config
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data
      - minecraft-private-data:/server/private:ro
      - minecraft-public-data:/server/public:ro

  # Uses manymine to do LAN announcements for both containers
  # Does require docker access itself.
  manymine:
    image: illiteratealliterator/manymine
    restart: always
    container_name: manymine
    ports:
      - '19132:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  private:
    image: itzg/minecraft-bedrock-server
    restart: always
    container_name: minecraft-private
    # Reminder that port 2222 is used inside this stack.
    expose:
      - 2222
    # Make the minecraft server port public
    ports:
      - 60601:19132/udp
    environment:
      # Enable SSH
      ENABLE_SSH: "TRUE"
      # Server settings
      EULA: "TRUE"
    volumes:
      - minecraft-private-data:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true

  public:
    image: itzg/minecraft-bedrock-server
    restart: always
    container_name: minecraft-public
    # Reminder that port 2222 is used inside this stack.
    expose:
      - 2222
    # Make the minecraft server port public
    ports:
      - 60602:19132/udp
    environment:
      # Enable SSH
      ENABLE_SSH: "TRUE"
      # Server settings
      EULA: "TRUE"
    volumes:
      - minecraft-public-data:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true

  restore:
    image: kaiede/minecraft-bedrock-backup
    profiles:
      - restore
    entrypoint: ["/opt/bedrock/bedrockifier", "restore"]
    network_mode: "none"
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data:ro
      - minecraft-private-data:/server/private
      - minecraft-public-data:/server/public
    stdin_open: true
    tty: true

volumes:
  # Allows backup to store persistent configuration for itself
  minecraft-backup:

  # Volume for backup data.
  minecraft-server-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCKIFIER_BACKUPS_DIR:-${PWD}/data/backups}

  # Private/Internal Server Data
  minecraft-private-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PRIVATE_SERVER_DATA_DIR:-${PWD}/data/private}

  # Public Server Data
  minecraft-public-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PUBLIC_SERVER_DATA_DIR:-${PWD}/data/public}
