version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft images start before the backup
    depends_on:
      - "public"
      - "private"
    environment:
      # Useful for making sure your logs have a proper timestamp
      TZ: ${TZ:-America/Los_Angeles}
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data
      - bedrock-private-data:/bedrock_private:ro
      - bedrock-public-data:/bedrock_public:ro

  # Uses manymine to do LAN announcements for both containers
  # Does require docker access itself.
  manymine:
    image: illiteratealliterator/manymine
    restart: always
    container_name: manymine
    ports:
      - '19132:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  private:
    image: itzg/minecraft-bedrock-server
    restart: always
    container_name: bedrock_private
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    # Make the minecraft server port public
    ports:
      - 60601:19132/udp
    environment:
      # Enable SSH
      ENABLE_SSH: "TRUE"
      # Server settings
      EULA: "TRUE"
    volumes:
      - bedrock-private-data:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true

  public:
    image: itzg/minecraft-bedrock-server
    restart: always
    container_name: bedrock_public
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    # Make the minecraft server port public
    ports:
      - 60602:19132/udp
    environment:
      # Enable SSH
      ENABLE_SSH: "TRUE"
      # Server settings
      EULA: "TRUE"
    volumes:
      - bedrock-public-data:/data
    stdin_open: true
    tty: true
    labels:
      - manymine.enable=true

  restore-menu:
    image: kaiede/minecraft-bedrock-backup
    profiles:
      - restore
    entrypoint: ["/opt/bedrock/restore-menu.sh"]
    network_mode: "none"
    environment:
      TZ: ${TZ:-America/Los_Angeles}
      TERM: "xterm-256color"
      BACKUP_DIR: "/data"
      RESTORE_UID: ${UID:-1000}
      RESTORE_GID: ${GID:-1000}
      RESTORE_MODE: ${RESTORE_MODE:-}
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data:ro
      - bedrock-private-data:/bedrock_private
      - bedrock-public-data:/bedrock_public
    stdin_open: true
    tty: true

volumes:
  minecraft-server-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCKIFIER_BACKUPS_DIR:-/opt/minecraft/backups}

  bedrock-private-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCK_PRIVATE_DATA_DIR:-/opt/bedrock/private}

  bedrock-public-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCK_PUBLIC_DATA_DIR:-/opt/bedrock/public}
