containers:
  bedrock:
    # Backup the world "PublicSMP" on the "bedrock_public" docker container
    - name: bedrock_public
      # Tells the backup service that this container is accessible
      # using the mc-server-runner SSH functionality.
      # passwordFile should point to the .rcon-cli.yaml file in the container
      ssh: public:2222
      passwordFile: /bedrock_public/.rcon-cli.yaml
      worlds:
        - /bedrock_public/worlds/PublicSMP
schedule:
  # This will perform a backup every 3 hours.
  # At most this will generate 8 backups a day.
  interval: 3h
trim:
  # Keep all backups for the last two days (today and yesterday)
  # Keep at least one backup for the last 14 days
  # Keep at least two backups per world
  trimDays: 2
  keepDays: 14
  minKeep: 2
