version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      - "public"
    environment:
        TZ: "America/Los_Angeles"
    volumes:
      # Docker needs to be made accessible to the backup container in this case
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/minecraft/backups:/backups
      - /opt/minecraft/public:/public

  public:
    image: itzg/minecraft-server
    container_name: minecraft_public
    # Make the minecraft server port public
    ports:
      - 25565:25565
    environment:
      # Server Settings
      TYPE: "FABRIC"
      EULA: "TRUE"
      MAX_PLAYERS: 6
      VIEW_DISTANCE: 20
      LEVEL: "PublicSMP"
      MOTD: "Public SMP Server"
      MEMORY: "2G"
    volumes:
      - /opt/minecraft/public:/data
    tty: true
    stdin_open: true
    restart: unless-stopped
