#!/usr/bin/env bash
set -euo pipefail

# LLM Disclosure
# This project was developed using AI agent(s) and/or AI code generation. The codebases principles, architecture decisions, and design element were scoped and refined by me. All code generated by LLMs was reviewed and tested to the best of my abilities. 

export TERM="${TERM:-xterm-256color}"

BACKUP_DIR="${BACKUP_DIR:-/data}"
RESTORE_CONFIG_PATH="${RESTORE_CONFIG_PATH:-}" # /config | /data | /backups
RESTORE_UID="${RESTORE_UID:-}"
RESTORE_GID="${RESTORE_GID:-}"
RESTORE_MODE="${RESTORE_MODE:-}"

DIALOG_BIN="${DIALOG_BIN:-dialog}"
TOOL_BIN="${TOOL_BIN:-/opt/bedrock/bedrockifier-tool}"
ASSUME_YES=0
RESTORE_FILE=""
TARGET_CONTAINER_NAME=""
INTERACTIVE=1
TERM_LINES=24
TERM_COLS=80
BOX_HEIGHT=0
BOX_WIDTH=0
MENU_HEIGHT=0
MENU_WIDTH=0
MENU_LIST_HEIGHT=0
MENU_BEGIN_Y=0
MENU_BEGIN_X=0

declare -a TARGET_LINES=()
declare -a BACKUP_CANDIDATE_LINES=()
SELECTED_TARGET_LINE=""
SELECTED_BACKUP_FILE=""

usage() {
  cat <<'EOF'
Usage: restore-menu.sh [options]

Interactive restore (default):
  restore-menu.sh

Non-interactive restore:
  restore-menu.sh --file <backup.mcworld|backup.zip> [--target <container-name>] --yes

Options:
  -f, --file <path>   Backup file to restore (name in BACKUP_DIR or a path)
  -t, --target <name> Restore to the named server container from config.yml
  -y, --yes           Confirm the restore when running non-interactively
  -h, --help          Show this help
EOF
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -f|--file)
        if [[ $# -lt 2 || -z "${2:-}" ]]; then
          echo "Missing value for $1" >&2
          usage >&2
          exit 2
        fi
        RESTORE_FILE="$2"
        shift 2
        ;;
      --file=*)
        RESTORE_FILE="${1#*=}"
        shift
        ;;
      -t|--target)
        if [[ $# -lt 2 || -z "${2:-}" ]]; then
          echo "Missing value for $1" >&2
          usage >&2
          exit 2
        fi
        TARGET_CONTAINER_NAME="$2"
        shift 2
        ;;
      --target=*)
        TARGET_CONTAINER_NAME="${1#*=}"
        shift
        ;;
      -y|--yes)
        ASSUME_YES=1
        shift
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      --)
        shift
        break
        ;;
      *)
        echo "Unknown option: $1" >&2
        usage >&2
        exit 2
        ;;
    esac
  done

  if [[ -n "$RESTORE_FILE" ]]; then
    INTERACTIVE=0
  fi

  if ((INTERACTIVE == 0)) && ((ASSUME_YES == 0)); then
    echo "Non-interactive restore requires --yes to proceed." >&2
    usage >&2
    exit 2
  fi
}

cleanup_terminal() {
  local has_tty=0

  if [[ -t 0 || -t 1 || -t 2 ]]; then
    has_tty=1
  fi

  if ((INTERACTIVE && has_tty)) && command -v "$DIALOG_BIN" >/dev/null 2>&1; then
    "$DIALOG_BIN" --clear || true
  fi
  if ((INTERACTIVE && has_tty)) && command -v tput >/dev/null 2>&1; then
    tput rmcup || true
    tput sgr0 || true
    tput op || true
    tput cnorm || true
  fi
  if ((INTERACTIVE && has_tty)) && command -v stty >/dev/null 2>&1; then
    stty sane || true
  fi
  if ((INTERACTIVE && has_tty)); then
    printf '\033[?1049l' || true
    clear || true
  fi
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1" >&2
    exit 1
  }
}

parse_args "$@"

if ((INTERACTIVE)); then
  require_cmd "$DIALOG_BIN"
fi
require_cmd "$TOOL_BIN"
require_cmd awk
require_cmd find
require_cmd numfmt
require_cmd stat
trap cleanup_terminal EXIT

init_terminal_size() {
  local size

  if ((INTERACTIVE == 0)); then
    return 0
  fi

  if size="$(stty size 2>/dev/null)"; then
    TERM_LINES="${size%% *}"
    TERM_COLS="${size##* }"
    return 0
  fi

  TERM_LINES="$(tput lines 2>/dev/null || echo 24)"
  TERM_COLS="$(tput cols 2>/dev/null || echo 80)"
}

clamp() {
  local value="$1"
  local min_value="$2"
  local max_value="$3"

  if ((max_value < min_value)); then
    max_value="$min_value"
  fi
  if ((value < min_value)); then
    value="$min_value"
  fi
  if ((value > max_value)); then
    value="$max_value"
  fi

  printf '%s\n' "$value"
}

max_text_width() {
  awk 'length > max { max = length } END { print max + 0 }' <<< "$1"
}

render_text() {
  printf '%b' "$1"
}

count_wrapped_lines() {
  local text="$1"
  local width="$2"

  awk -v width="$width" '
    BEGIN {
      total = 0
      if (width < 1) {
        width = 1
      }
    }
    {
      line_length = length($0)
      if (line_length == 0) {
        total += 1
      } else {
        total += int((line_length - 1) / width) + 1
      }
    }
    END {
      print total > 0 ? total : 1
    }
  ' <<< "$text"
}

compute_box_dims() {
  local text
  local min_height="${2:-8}"
  local min_width="${3:-50}"
  local text_width
  local usable_width
  local wrapped_line_count

  text="$(render_text "$1")"
  init_terminal_size
  text_width="$(max_text_width "$text")"

  BOX_WIDTH="$(clamp "$((text_width + 8))" "$min_width" "$((TERM_COLS - 2))")"
  usable_width="$(clamp "$((BOX_WIDTH - 6))" 20 "$BOX_WIDTH")"
  wrapped_line_count="$(count_wrapped_lines "$text" "$usable_width")"
  BOX_HEIGHT="$(clamp "$((wrapped_line_count + 6))" "$min_height" "$((TERM_LINES - 2))")"
}

compute_menu_dims() {
  local prompt="$1"
  shift
  local item_count=0
  local max_width
  local max_height
  local top_margin=3
  local bottom_margin=3
  local tag
  local item
  local width

  init_terminal_size
  max_width="$(max_text_width "$prompt")"

  while (($# >= 2)); do
    tag="$1"
    item="$2"
    shift 2
    width=$(( ${#tag} + ${#item} + 3 ))
    if ((width > max_width)); then
      max_width="$width"
    fi
    ((item_count += 1))
  done

  max_height="$((TERM_LINES - top_margin - bottom_margin))"
  MENU_WIDTH="$(clamp "$((max_width + 8))" 60 "$((TERM_COLS - 4))")"
  MENU_HEIGHT="$(clamp "$((item_count + 8))" 13 "$max_height")"
  MENU_LIST_HEIGHT="$(clamp "$item_count" 1 "$((MENU_HEIGHT - 7))")"
  MENU_BEGIN_Y="$top_margin"
  MENU_BEGIN_X="$(clamp "$(((TERM_COLS - MENU_WIDTH) / 2))" 0 "$((TERM_COLS - MENU_WIDTH))")"
}

show_msgbox() {
  local title="$1"
  local text="$2"
  local min_height="${3:-8}"
  local min_width="${4:-50}"
  local stream="${5:-stdout}"
  local prefix="${6:-}"

  text="$(render_text "$text")"
  if ((INTERACTIVE)); then
    compute_box_dims "$text" "$min_height" "$min_width"
    "$DIALOG_BIN" --clear --trim --cr-wrap --title "$title" --msgbox "$text" "$BOX_HEIGHT" "$BOX_WIDTH" || true
    return 0
  fi

  if [[ "$stream" == "stderr" ]]; then
    printf '%s%b\n' "$prefix" "$text" >&2
    return 0
  fi

  printf '%b\n' "$text"
}

show_yesno() {
  local title="$1"
  local text="$2"
  local min_height="${3:-8}"
  local min_width="${4:-50}"
  local status

  text="$(render_text "$text")"

  if ((INTERACTIVE == 0)); then
    printf '%b\n' "$text"
    return 0
  fi

  compute_box_dims "$text" "$min_height" "$min_width"
  set +e
  "$DIALOG_BIN" --clear --trim --cr-wrap --title "$title" --yesno "$text" "$BOX_HEIGHT" "$BOX_WIDTH"
  status=$?
  set -e
  return "$status"
}

notify() {
  show_msgbox "$1" "$2" "${3:-8}" "${4:-50}"
}

notify_error() {
  show_msgbox "Restore Error" "$1" 8 50 stderr "ERROR: "
}

resolve_config_path() {
  local config_file="${CONFIG_FILE:-config.yml}"
  local candidate
  local -a candidates=()

  if [[ -n "$RESTORE_CONFIG_PATH" ]]; then
    if [[ -f "$RESTORE_CONFIG_PATH" ]]; then
      printf '%s' "$RESTORE_CONFIG_PATH"
      return 0
    fi
    return 1
  fi

  if [[ -n "${CONFIG_DIR:-}" ]]; then
    candidates+=("${CONFIG_DIR%/}/${config_file}")
  fi
  candidates+=("/config/${config_file}")

  if [[ -n "${DATA_DIR:-}" ]]; then
    candidates+=("${DATA_DIR%/}/${config_file}")
  fi
  candidates+=("/data/${config_file}" "/backups/${config_file}")

  for candidate in "${candidates[@]}"; do
    if [[ -f "$candidate" ]]; then
      printf '%s' "$candidate"
      return 0
    fi
  done

  return 1
}

run_list_restore_targets() {
  local config_path

  config_path="$(resolve_config_path)" || return 1

  awk '
    function trim(value) {
      gsub(/\r/, "", value)
      sub(/^[[:space:]]+/, "", value)
      sub(/[[:space:]]+$/, "", value)
      return value
    }

    function dirname(path, copy) {
      copy = path
      sub(/\/[^/]+$/, "", copy)
      return copy == "" ? "/" : copy
    }

    function basename(path, copy) {
      copy = path
      sub(/^.*\//, "", copy)
      return copy
    }

    function emit_target(edition, container_name, world_path, prefixed, world_name, restore_root) {
      world_name = basename(world_path)
      restore_root = dirname(world_path)
      gsub(/\t/, " ", world_name)
      gsub(/\n/, " ", world_name)
      gsub(/\t/, " ", restore_root)
      gsub(/\n/, " ", restore_root)
      gsub(/\t/, " ", world_path)
      gsub(/\n/, " ", world_path)
      print edition "\t" container_name "\t" world_name "\t" restore_root "\t" prefixed "\t" world_path
    }

    BEGIN {
      global_prefix = "false"
      section = ""
      edition = ""
      container_name = ""
      container_prefix = ""
      in_worlds = 0
    }

    /^[[:space:]]*#/ { next }

    {
      raw = $0
      sub(/[[:space:]]+#.*$/, "", raw)
      if (trim(raw) == "") {
        next
      }

      indent = match(raw, /[^ ]/) - 1
      text = substr(raw, indent + 1)

      if (indent == 0) {
        section = ""
        edition = ""
        container_name = ""
        container_prefix = ""
        in_worlds = 0

        if (text ~ /^prefixContainerName:[[:space:]]*(true|false)$/) {
          split(text, parts, ":")
          global_prefix = trim(parts[2])
        } else if (text == "containers:") {
          section = "containers"
        }
        next
      }

      if (section != "containers") {
        next
      }

      if (indent == 2) {
        in_worlds = 0
        container_name = ""
        container_prefix = ""

        if (text == "bedrock:") {
          edition = "bedrock"
        } else if (text == "java:") {
          edition = "java"
        } else {
          edition = ""
        }
        next
      }

      if (edition == "") {
        next
      }

      if (indent == 4) {
        in_worlds = 0
        container_prefix = ""

        if (text ~ /^-[[:space:]]*name:[[:space:]]*/) {
          container_name = text
          sub(/^-+[[:space:]]*name:[[:space:]]*/, "", container_name)
          container_name = trim(container_name)
        }
        next
      }

      if (indent == 6) {
        if (text ~ /^name:[[:space:]]*/) {
          container_name = text
          sub(/^name:[[:space:]]*/, "", container_name)
          container_name = trim(container_name)
          next
        }

        if (text ~ /^prefixContainerName:[[:space:]]*(true|false)$/) {
          container_prefix = text
          sub(/^prefixContainerName:[[:space:]]*/, "", container_prefix)
          container_prefix = trim(container_prefix)
          next
        }

        if (text == "worlds:") {
          in_worlds = 1
          next
        }

        if (text ~ /^[[:alpha:]][[:alnum:]]*:/) {
          in_worlds = 0
          next
        }
      }

      if (indent == 8 && in_worlds && text ~ /^-[[:space:]]*/) {
        world_path = text
        sub(/^-+[[:space:]]*/, "", world_path)
        prefixed = (global_prefix == "true" || container_prefix == "true") ? "true" : "false"
        emit_target(edition, container_name, trim(world_path), prefixed)
      }
    }
  ' "$config_path"
}

load_targets() {
  local targets_output=""

  if ! targets_output="$(run_list_restore_targets)"; then
    notify_error "Unable to load restore targets from config.yml.\n\nEnsure the restore container can read the same Bedrockifier config used by the backup service."
    return 1
  fi

  TARGET_LINES=()
  if [[ -n "$targets_output" ]]; then
    mapfile -t TARGET_LINES <<< "$targets_output"
  fi

  if ((${#TARGET_LINES[@]} == 0)); then
    notify_error "No restore targets were found in config.yml."
    return 1
  fi
}

parse_target_line() {
  local line="$1"
  IFS=$'\t' read -r TARGET_EDITION TARGET_CONTAINER TARGET_WORLD TARGET_RESTORE_ROOT TARGET_PREFIXED TARGET_RESTORE_PATH <<< "$line"
}

set_selected_target_from_line() {
  SELECTED_TARGET_LINE="$1"
  parse_target_line "$SELECTED_TARGET_LINE"
  SELECTED_EDITION="$TARGET_EDITION"
  SELECTED_CONTAINER="$TARGET_CONTAINER"
  SELECTED_WORLD="$TARGET_WORLD"
  SELECTED_RESTORE_ROOT="$TARGET_RESTORE_ROOT"
  SELECTED_PREFIXED="$TARGET_PREFIXED"
  SELECTED_RESTORE_PATH="$TARGET_RESTORE_PATH"
}

backup_extension_for_edition() {
  if [[ "$1" == "bedrock" ]]; then
    printf 'mcworld'
  else
    printf 'zip'
  fi
}

is_extras_archive() {
  [[ "$1" == *.extras.*.zip ]]
}

backup_stem_for_target() {
  local base="$1"
  local ext="$2"
  local container="$3"
  local prefixed="$4"
  local stem

  stem="${base%."$ext"}"

  if [[ "$prefixed" == "true" ]]; then
    if [[ "$stem" != "${container}."* ]]; then
      return 1
    fi
    stem="${stem#"${container}."}"
  fi

  printf '%s' "$stem"
}

backup_matches_target_exact() {
  local base="$1"
  local edition="$2"
  local container="$3"
  local world="$4"
  local prefixed="$5"
  local ext
  local stem

  if is_extras_archive "$base"; then
    return 1
  fi

  ext="$(backup_extension_for_edition "$edition")"
  if [[ "$base" != *".${ext}" ]]; then
    return 1
  fi

  stem="$(backup_stem_for_target "$base" "$ext" "$container" "$prefixed")" || return 1
  [[ "$stem" == "${world}."* ]]
}

has_unprefixed_collision() {
  local edition="$1"
  local world="$2"
  local count=0
  local line

  for line in "${TARGET_LINES[@]}"; do
    parse_target_line "$line"
    if [[ "$TARGET_PREFIXED" == "true" ]]; then
      continue
    fi
    if [[ "$TARGET_EDITION" == "$edition" && "$TARGET_WORLD" == "$world" ]]; then
      ((count+=1))
    fi
  done

  ((count > 1))
}

basename_claimed_by_prefixed_target() {
  local edition="$1"
  local base="$2"
  local line

  for line in "${TARGET_LINES[@]}"; do
    parse_target_line "$line"
    if [[ "$TARGET_EDITION" != "$edition" || "$TARGET_PREFIXED" != "true" ]]; then
      continue
    fi
    if [[ "$base" == "${TARGET_CONTAINER}."* ]]; then
      return 0
    fi
  done

  return 1
}

target_line_matches_backup() {
  local line="$1"
  local base="$2"
  local allow_unprefixed_collisions="${3:-0}"
  local edition
  local container
  local world
  local prefixed

  parse_target_line "$line"
  edition="$TARGET_EDITION"
  container="$TARGET_CONTAINER"
  world="$TARGET_WORLD"
  prefixed="$TARGET_PREFIXED"

  if [[ "$prefixed" == "true" ]]; then
    [[ "$base" == "${container}."* ]] || return 1
  else
    if basename_claimed_by_prefixed_target "$edition" "$base"; then
      return 1
    fi
    if ((allow_unprefixed_collisions == 0)) && has_unprefixed_collision "$edition" "$world"; then
      return 1
    fi
  fi

  backup_matches_target_exact "$base" "$edition" "$container" "$world" "$prefixed"
}

matching_target_lines_for_backup() {
  local backup_file="$1"
  local allow_unprefixed_collisions="${2:-0}"
  local base
  local line

  base="$(basename "$backup_file")"

  for line in "${TARGET_LINES[@]}"; do
    if target_line_matches_backup "$line" "$base" "$allow_unprefixed_collisions"; then
      printf '%s\n' "$line"
    fi
  done
}

collect_backups() {
  if [[ ! -d "$BACKUP_DIR" ]]; then
    return 0
  fi

  find "$BACKUP_DIR" -maxdepth 1 -type f \( -name '*.mcworld' -o -name '*.zip' \) \
    -printf '%T@\t%p\n' 2>/dev/null | sort -rn | cut -f2-
}

resolve_archive_path() {
  local backup_ref="$1"

  if [[ "$backup_ref" == */* ]]; then
    printf '%s' "$backup_ref"
  else
    printf '%s/%s' "$BACKUP_DIR" "$backup_ref"
  fi
}

resolve_restore_owner() {
  local uid gid owner

  uid="$RESTORE_UID"
  gid="$RESTORE_GID"

  if [[ -z "$uid" || -z "$gid" ]]; then
    if owner="$(stat -c '%u:%g' "$(dirname "$SELECTED_RESTORE_PATH")" 2>/dev/null)"; then
      uid="${uid:-${owner%%:*}}"
      gid="${gid:-${owner##*:}}"
    fi
  fi

  uid="${uid:-1000}"
  gid="${gid:-1000}"

  printf '%s:%s' "$uid" "$gid"
}

apply_restore_owner() {
  local dest="$1"
  local owner

  owner="$(resolve_restore_owner)"
  chown -R "$owner" "$dest"
}

apply_restore_permissions() {
  local dest="$1"

  if [[ -z "$RESTORE_MODE" ]]; then
    return 0
  fi

  chmod -R -- "$RESTORE_MODE" "$dest"
}

cleanup_paths() {
  local path

  for path in "$@"; do
    if [[ -n "$path" && -e "$path" ]]; then
      rm -rf -- "$path"
    fi
  done
}

select_target() {
  local -a menu_items
  local line
  local index=1
  local prompt="Choose the configured server/world to restore:"
  local choice
  local status

  if ((${#TARGET_LINES[@]} == 1)); then
    set_selected_target_from_line "${TARGET_LINES[0]}"
    return 0
  fi

  for line in "${TARGET_LINES[@]}"; do
    parse_target_line "$line"
    menu_items+=(
      "$index"
      "${TARGET_CONTAINER}  [${TARGET_EDITION}]  ${TARGET_WORLD}  ->  ${TARGET_RESTORE_PATH}"
    )
    ((index+=1))
  done

  compute_menu_dims "$prompt" "${menu_items[@]}"
  set +e
  choice=$(
    "$DIALOG_BIN" --clear --stdout --title "Select Restore Target" \
      --menu "$prompt" \
      "$MENU_HEIGHT" "$MENU_WIDTH" "$MENU_LIST_HEIGHT" \
      "${menu_items[@]}"
  )
  status=$?
  set -e

  if ((status != 0)); then
    return 1
  fi

  set_selected_target_from_line "${TARGET_LINES[$((choice - 1))]}"
}

collect_backup_candidates() {
  local -a files
  local file
  local base

  BACKUP_CANDIDATE_LINES=()
  mapfile -t files < <(collect_backups)

  for file in "${files[@]}"; do
    base="$(basename "$file")"

    if is_extras_archive "$base"; then
      continue
    fi

    if target_line_matches_backup "$SELECTED_TARGET_LINE" "$base"; then
      BACKUP_CANDIDATE_LINES+=("$file")
    fi
  done
}

select_backup() {
  local -a menu_items
  local file
  local base
  local size_bytes
  local size_h
  local mod_time
  local prompt
  local status
  local expected_pattern

  collect_backup_candidates

  if ((${#BACKUP_CANDIDATE_LINES[@]} == 0)); then
    if [[ "$SELECTED_PREFIXED" == "true" ]]; then
      expected_pattern="${SELECTED_CONTAINER}.${SELECTED_WORLD}.<timestamp>.$(backup_extension_for_edition "$SELECTED_EDITION")"
    else
      expected_pattern="${SELECTED_WORLD}.<timestamp>.$(backup_extension_for_edition "$SELECTED_EDITION")"
    fi

    notify "No Matching Backups" "No matching backups were found for the selected server/world.\n\nServer: ${SELECTED_CONTAINER}\nWorld: ${SELECTED_WORLD}\nFolder: ${BACKUP_DIR}\n\nThe filename filter did not match any backups.\nExpected pattern: ${expected_pattern}\n\nIf this target shares a backup folder with other servers, enable prefixContainerName in config.yml." 14 76
    return 2
  fi

  for file in "${BACKUP_CANDIDATE_LINES[@]}"; do
    base="$(basename "$file")"
    size_bytes="$(stat -c '%s' "$file")"
    size_h="$(numfmt --to=iec --suffix=B "$size_bytes")"
    mod_time="$(stat -c '%y' "$file" | cut -d. -f1)"
    menu_items+=("$base" "${mod_time}  ${size_h}")
  done

  prompt="Choose a backup for ${SELECTED_CONTAINER} / ${SELECTED_WORLD}:"$'\n\n\n'
  compute_menu_dims "$prompt" "${menu_items[@]}"
  set +e
  SELECTED_BACKUP_FILE=$(
    "$DIALOG_BIN" --clear --begin "$MENU_BEGIN_Y" "$MENU_BEGIN_X" --stdout --title "Select Backup" \
      --menu "$prompt" \
      "$MENU_HEIGHT" "$MENU_WIDTH" "$MENU_LIST_HEIGHT" \
      "${menu_items[@]}"
  )
  status=$?
  set -e

  if ((status != 0)); then
    return 3
  fi
  return 0
}

choose_target_for_archive() {
  local archive="$1"
  local -a candidates
  local -a filtered_candidates
  local candidate

  mapfile -t candidates < <(matching_target_lines_for_backup "$archive" 1)

  if [[ -n "$TARGET_CONTAINER_NAME" ]]; then
    for candidate in "${candidates[@]}"; do
      parse_target_line "$candidate"
      if [[ "$TARGET_CONTAINER" == "$TARGET_CONTAINER_NAME" ]]; then
        filtered_candidates+=("$candidate")
      fi
    done
    candidates=("${filtered_candidates[@]}")
  fi

  if ((${#candidates[@]} == 0)); then
    if [[ -n "$TARGET_CONTAINER_NAME" ]]; then
      notify_error "Unable to match the archive to the configured restore target '${TARGET_CONTAINER_NAME}'.\n\nVerify the config, archive naming, and selected container."
    else
      notify_error "Unable to match the archive to any configured restore target.\n\nUse the interactive workflow or verify the config and backup naming."
    fi
    return 1
  fi

  if ((${#candidates[@]} > 1)); then
    notify_error "The archive matches multiple restore targets.\n\nUse --target <container-name>, enable prefixContainerName for colliding targets, or use the interactive workflow."
    return 1
  fi

  set_selected_target_from_line "${candidates[0]}"
}

confirm_action() {
  local backup="$1"
  local restore_path="$2"
  local action_text="This will replace the existing world at:\n  ${restore_path}"
  local prompt
  local status

  if [[ ! -d "$restore_path" ]]; then
    action_text="This will restore into:\n  ${restore_path}"
  fi

  prompt="Restore:\n  ${backup}\n\nTarget:\n  ${SELECTED_CONTAINER} [${SELECTED_EDITION}] ${SELECTED_WORLD}\n\n${action_text}\n\nProceed?"
  show_yesno "Confirm Restore" "$prompt" 14 60
  status=$?
  return $status
}

restore_backup() {
  local backup_file="$1"
  local archive
  local backup_label

  archive="$(resolve_archive_path "$backup_file")"
  backup_label="$(basename "$backup_file")"

  if [[ ! -f "$archive" ]]; then
    notify_error "Backup file not found: ${archive}"
    return 1
  fi

  mkdir -p "$SELECTED_RESTORE_ROOT"
  if [[ -e "$SELECTED_RESTORE_PATH" ]]; then
    cleanup_paths "$SELECTED_RESTORE_PATH"
  fi

  if ! "$TOOL_BIN" unpack "$archive" "$SELECTED_RESTORE_ROOT" >/dev/null; then
    notify_error "Restore failed while unpacking:\n  ${backup_label}"
    return 1
  fi

  if [[ ! -d "$SELECTED_RESTORE_PATH" ]]; then
    notify_error "Restore completed, but the configured target path was not created:\n  ${SELECTED_RESTORE_PATH}\n\nCheck the backup contents and config.yml before continuing."
    return 1
  fi

  if ! apply_restore_owner "$SELECTED_RESTORE_PATH"; then
    notify_error "Restore completed, but failed to set ownership on:\n  ${SELECTED_RESTORE_PATH}\n\nCheck RESTORE_UID/RESTORE_GID and permissions."
    return 1
  fi

  if ! apply_restore_permissions "$SELECTED_RESTORE_PATH"; then
    notify_error "Restore completed, but failed to set permissions on:\n  ${SELECTED_RESTORE_PATH}\n\nCheck RESTORE_MODE and permissions."
    return 1
  fi

  notify "Restore Complete" "Restore Complete\nTarget: ${SELECTED_CONTAINER} [${SELECTED_EDITION}] ${SELECTED_WORLD}\nBackup: ${backup_label}\nPath: ${SELECTED_RESTORE_PATH}"
}

main() {
  local backup_file
  local intro_text
  local status
  local return_to_target=0

  load_targets || exit 1

  if ((INTERACTIVE == 0)); then
    backup_file="$(resolve_archive_path "$RESTORE_FILE")"
    if ! choose_target_for_archive "$backup_file"; then
      exit 1
    fi

    if ! restore_backup "$backup_file"; then
      exit 1
    fi
    exit 0
  fi

  intro_text="===============================\n   Minecraft World Restore\n===============================\n\nThis tool restores a selected Minecraft world backup into the configured world path from Bedrockifier's config.yml.\n\nRecommended workflow:\n- stop the Minecraft server(s)\n- stop backup writes\n- run this restore helper\n\nUses the same config.yml as Bedrockifier."
  "$DIALOG_BIN" --clear --trim --cr-wrap --title "Restore Menu" --msgbox "$intro_text" "17" "64"

  while true; do
    select_target || { clear; exit 0; }
    return_to_target=0

    while true; do
      if select_backup; then
        status=0
      else
        status=$?
      fi

      if ((status == 2)); then
        return_to_target=1
        break
      fi
      if ((status == 3)); then
        return_to_target=1
        break
      fi
      if ((status != 0)); then
        break
      fi

      backup_file="$SELECTED_BACKUP_FILE"
      confirm_action "$backup_file" "$SELECTED_RESTORE_PATH" || break
      restore_backup "$backup_file" || true
      clear || true
      exit 0
    done

    if ((return_to_target)); then
      continue
    fi
  done
  clear || true
}

main
