services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft image starts before the backup
    depends_on:
      - "server"
    environment:
      # Local timezone to reduce confusion
      TZ: ${TZ:-America/Los_Angeles}
    volumes:
      - minecraft-backup:/config
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data
      - minecraft-server-data:/server:ro

  server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    # Reminder that port 2222 is used inside this stack.
    expose:
      - 25575
    # Make the minecraft server port public
    ports:
      - 25565:25565
    environment:
      # Enable RCON
      ENABLE_RCON: "TRUE"
      # Server Settings
      TYPE: "FABRIC"
      EULA: "TRUE"
      MAX_PLAYERS: 6
      VIEW_DISTANCE: 20
      LEVEL: "PublicSMP"
      MOTD: "Public SMP Server"
      MEMORY: "2G"
    volumes:
      - minecraft-server-data:/data
    restart: unless-stopped

  restore:
    image: kaiede/minecraft-bedrock-backup
    profiles:
      - restore
    entrypoint: ["/opt/bedrock/bedrockifier", "restore"]
    network_mode: "none"
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data:ro
      - minecraft-server-data:/server
    stdin_open: true
    tty: true

volumes:
  # Allows backup to store persistent configuration for itself
  minecraft-backup:
  
  # Volume for backup data.
  minecraft-server-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCKIFIER_BACKUPS_DIR:-/opt/minecraft/backups}

  # Minecraft Server Data
  minecraft-server-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MINECRAFT_SERVER_DATA_DIR:-/opt/minecraft/public}
