version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft image starts before the backup
    depends_on:
      - "public"
    environment:
      # Useful for making sure your logs have a proper timestamp
      TZ: ${TZ:-America/Los_Angeles}
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data
      - java-public-data:/public:ro

  public:
    image: itzg/minecraft-server
    container_name: minecraft_public
    # Expose the minecraft server's RCON port just to the backup container
    expose:
      - 25575
    # Make the minecraft server port public
    ports:
      - 25565:25565
    environment:
      # Enable RCON
      ENABLE_RCON: "TRUE"
      # Server Settings
      TYPE: "FABRIC"
      EULA: "TRUE"
      MAX_PLAYERS: 6
      VIEW_DISTANCE: 20
      LEVEL: "PublicSMP"
      MOTD: "Public SMP Server"
      MEMORY: "2G"
    volumes:
      - java-public-data:/data
    restart: unless-stopped

  restore-menu:
    image: kaiede/minecraft-bedrock-backup
    profiles:
      - restore
    entrypoint: ["/opt/bedrock/restore-menu.sh"]
    network_mode: "none"
    environment:
      TZ: ${TZ:-America/Los_Angeles}
      TERM: "xterm-256color"
      BACKUP_DIR: "/data"
      RESTORE_UID: ${UID:-1000}
      RESTORE_GID: ${GID:-1000}
      RESTORE_MODE: ${RESTORE_MODE:-}
    volumes:
      - ./config.yml:/config/config.yml:ro
      - minecraft-server-backups:/data:ro
      - java-public-data:/public
    stdin_open: true
    tty: true

volumes:
  minecraft-server-backups:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BEDROCKIFIER_BACKUPS_DIR:-/opt/minecraft/backups}

  java-public-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${JAVA_PUBLIC_DATA_DIR:-/opt/minecraft/public}
