version: '3.7'

services:
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: always
    # Make sure the minecraft image starts before the backup
    depends_on:
      - "public"
    environment:
        # Useful for making sure your logs have a proper timestamp
        TZ: "America/Los_Angeles"
    volumes:
      # (Optional) Map a configuration folder separately from the backups.
      # - /opt/minecraft/backup-config:/config
      # Map your backups folder data /data
      - /opt/minecraft/backups:/data
      # Map your server's data folder
      - /opt/minecraft/public:/public

  public:
    image: itzg/minecraft-server
    container_name: minecraft_public
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    # Make the minecraft server port public
    ports:
      - 25565:25565
    environment:
      # Enables the SSH capability
      ENABLE_SSH: "TRUE"
      # Server Settings
      TYPE: "FABRIC"
      EULA: "TRUE"
      MAX_PLAYERS: 6
      VIEW_DISTANCE: 20
      LEVEL: "PublicSMP"
      MOTD: "Public SMP Server"
      MEMORY: "2G"
    volumes:
      - /opt/minecraft/public:/data
    restart: unless-stopped
