name: Docker CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

env:
  docker_tag: ${{ github.event_name != 'release' && 'test' || 'latest' }}

jobs:
  build:
    runs-on: ${{ matrix.host.runner }}
    name: Image ${{ matrix.host.arch }} (${{ matrix.variant.name }})
    if: github.repository == 'Kaiede/Bedrockifier'
    strategy:
      matrix:
        host: [{arch: 'amd64', runner: 'ubuntu-latest'}, {arch: 'arm64', runner: 'ubuntu-22.04-arm'}]
        variant: [{name: 'full', tag: ''}, {name: 'slim', tag: '-slim'}]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build ${{ matrix.arch }} - ${{ matrix.variant }}
      uses: docker/build-push-action@v7
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Docker/Dockerfile
        platforms: linux/${{ matrix.host.arch }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}-${{ matrix.host.arch }}${{ matrix.variant.tag }}
          kaiede/bedrockifier:${{ env.docker_tag }}-${{ matrix.host.arch }}${{ matrix.variant.tag }}
        build-args: |
          QEMU_CPU=max
          IMAGEVARIANT=${{ matrix.variant }}
          arch=${{ matrix.host.arch }}
          swift_base=${{ env.swift_base }}
          swift_version=${{ env.swift_version }}

    - name: Check Expected Output
      run: |
        echo Final Expected Images:
        echo   kaiede/bedrockifier:${{ env.docker_tag }}-${{ matrix.host.arch }}${{ matrix.variant.tag }}
        echo   kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}-${{ matrix.host.arch }}${{ matrix.variant.tag }}

  merge-tags:
    needs: ['build']
    runs-on: ubuntu-latest
    name: Merge Tags (${{ matrix.variant.name }})
    if: github.repository == 'Kaiede/Bedrockifier' && github.event_name != 'pull_request'
    strategy:
      matrix:
        variant: [{name: 'full', tag: ''}, {name: 'slim', tag: '-slim'}]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Make Manifest - ${{ env.docker_tag }}
      if: github.event_name != 'pull_request'
      run: bash Docker/merge.sh kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ matrix.variant.tag }} kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ matrix.variant.tag }}

    - name: Make Manifest - ${{ env.docker_tag }}
      if: github.event_name != 'pull_request'
      run: bash Docker/merge.sh kaiede/bedrockifier:${{ env.docker_tag }}${{ matrix.variant.tag }} kaiede/bedrockifier:${{ env.docker_tag }}${{ matrix.variant.tag }}

    - name: Get Release Tag
      id: tag
      if: github.event_name == 'release'
      uses: dawidd6/action-get-tag@v1

    - name: Make Manifest - ${{ steps.tag.outputs.tag }}
      if: github.event_name == 'release'
      run: bash Docker/merge.sh --semver kaiede/minecraft-bedrock-backup:${{ steps.tag.outputs.tag }}${{ matrix.variant.tag }} kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ matrix.variant.tag }}

    - name: Make Manifest - ${{ steps.tag.outputs.tag }}
      if: github.event_name == 'release'
      run: bash Docker/merge.sh --semver kaiede/bedrockifier:${{ steps.tag.outputs.tag }}${{ matrix.variant.tag }} kaiede/bedrockifier:${{ env.docker_tag }}${{ matrix.variant.tag }}
