name: Docker CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

env:
  docker_tag: ${{ github.event_name != 'release' && 'test' || 'latest' }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Image - ${{ matrix.os }} ${{ matrix.variant }}
    if: github.repository == 'Kaiede/Bedrockifier'
    env:
      arch: ${{ matrix.os == 'ubuntu-latest' && 'amd64' || 'arm64' }}
      tag_suffix: ${{ matrix.variant != 'full' && format('-{0}', matrix.variant) || '' }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-24.04-arm']
        variant: ['full', 'slim']

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build ${{ env.arch }} - ${{ matrix.variant }}
      uses: docker/build-push-action@v7
      with:
        builder: ${{ steps.buildx.outputs.name }}
        context: .
        file: ./Docker/Dockerfile
        platforms: linux/${{ env.arch }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}-${{ env.arch }}${{env.tag_suffix}}
          kaiede/bedrockifier:${{ env.docker_tag }}-${{ env.arch }}${{env.tag_suffix}}
        build-args: |
          QEMU_CPU=max
          IMAGEVARIANT=${{ matrix.variant }}
          arch=${{ env.arch }}
          swift_base=${{ env.swift_base }}
          swift_version=${{ env.swift_version }}

    - name: Check Expected Output
      run: |
        echo Final Expected Images:
        echo   kaiede/bedrockifier:${{ env.docker_tag }}-${{ env.arch }}${{env.tag_suffix}}
        echo   kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}-${{ env.arch }}${{env.tag_suffix}}

  merge-tags:
    needs: ['build']
    runs-on: ubuntu-latest
    name: Merge Tags - ${{ matrix.variant }}
    if: github.repository == 'Kaiede/Bedrockifier' && github.event_name != 'pull_request'
    env:
      tag_suffix: ${{ matrix.variant != 'full' && format('-{0}', matrix.variant) || '' }}
    strategy:
      matrix:
        variant: ['full', 'slim']

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Make Manifest - ${{ env.docker_tag }}
      if: github.event_name != 'pull_request'
      run: bash Docker/merge.sh kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ env.tag_suffix }} kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ env.tag_suffix }}

    - name: Make Manifest - ${{ env.docker_tag }}
      if: github.event_name != 'pull_request'
      run: bash Docker/merge.sh kaiede/bedrockifier:${{ env.docker_tag }}${{ env.tag_suffix }} kaiede/bedrockifier:${{ env.docker_tag }}${{ env.tag_suffix }}

    - name: Get Release Tag
      id: tag
      if: github.event_name == 'release'
      uses: dawidd6/action-get-tag@v1

    - name: Make Manifest - ${{ steps.tag.outputs.tag }}
      if: github.event_name == 'release'
      run: bash Docker/merge.sh --semver kaiede/minecraft-bedrock-backup:${{ steps.tag.outputs.tag }}${{ env.tag_suffix }} kaiede/minecraft-bedrock-backup:${{ env.docker_tag }}${{ env.tag_suffix }}

    - name: Make Manifest - ${{ steps.tag.outputs.tag }}
      if: github.event_name == 'release'
      run: bash Docker/merge.sh --semver kaiede/bedrockifier:${{ steps.tag.outputs.tag }}${{ env.tag_suffix }} kaiede/bedrockifier:${{ env.docker_tag }}${{ env.tag_suffix }}
