name: Deploy Wiki
on:
  release:
    types:
      - published
jobs:
  deploy-wiki:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions4gh/configure-wiki@v1
        with:
          path: Wiki
      - uses: actions4gh/deploy-wiki@v1
        with:
          path: Wiki
